server:
  port: 4452
spring:
  application:
    name: cloud-config-center-dev
  cloud:
    config:
      server:
        git:
          uri:  git@github.com:1299182905/cloud-config.git
          search-paths:
            - cloude-config
      label: main
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
config:
  info: dev2

